spring.application.name=gemsoul-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gemsoul?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allow serving static files from resources
spring.web.resources.static-locations=classpath:/static/
